package com.stalkerarmor;

/* AUTO-GENERATED by tools/gen_full_sets.py — do not edit by hand. */
public record StalkerFullSet(String id, String family, String texture) {
    public static final StalkerFullSet[] ALL = new StalkerFullSet[] {
        new StalkerFullSet("full_berill", "berill", "arm_berill_military.png"),
        new StalkerFullSet("full_bulat", "bulat", "arm_bulat_military.png"),
        new StalkerFullSet("full_heavy", "heavy", "arm_heavy_merc_1.png"),
        new StalkerFullSet("full_exo", "exo", "arm_heavy_merc_1.png"),
        new StalkerFullSet("full_jacket", "jacket", "arm_jacket.png"),
        new StalkerFullSet("full_kombez", "kombez", "arm_merc_kombez_1.png"),
        new StalkerFullSet("full_scientist", "scientist", "arm_scientist_1.png"),
        new StalkerFullSet("full_seva", "seva", "arm_seva_merc.png"),
        new StalkerFullSet("full_zarya", "zarya", "arm_zarya_stalker.png"),
        new StalkerFullSet("full_cape", "cape", "arm_cape.png"),
    };
}
